# Form implementation generated from reading ui file 'guiRocketConfig.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

class Ui_widRocketConfig(object):
    def setupUi(self, widRocketConfig):
        if not widRocketConfig.objectName():
            widRocketConfig.setObjectName(u"widRocketConfig")
        widRocketConfig.resize(209, 129)

class Ui_widRocketConfig(object):
    def x(input): print(input) # Temp var delete
    def setupUi(self, widRocketConfig):
        widRocketConfig.setObjectName("widget")
        widRocketConfig.resize(200, 130)
        
        self.labelRocketName = QtWidgets.QLabel(parent=widRocketConfig)
        self.labelRocketName.setGeometry(QtCore.QRect(0, 15, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.labelRocketName.setFont(font)
        self.labelRocketName.setObjectName("labelRocketName")
        
        self.editRocketMass = QtWidgets.QLineEdit(parent=widRocketConfig)
        self.editRocketMass.setGeometry(QtCore.QRect(100, 50, 100, 20))
        self.editRocketMass.setObjectName("editRocketMass")
        self.editRocketMass.editingFinished.connect(lambda: self.x(self.editRocketMass.text()))
        
        self.labelRocketMass = QtWidgets.QLabel(parent=widRocketConfig)
        self.labelRocketMass.setGeometry(QtCore.QRect(0, 50, 100, 16))
        self.labelRocketMass.setObjectName("labelRocketMass")
        
        self.labelCoeDrag = QtWidgets.QLabel(parent=widRocketConfig)
        self.labelCoeDrag.setGeometry(QtCore.QRect(0, 75, 100, 16))
        self.labelCoeDrag.setObjectName("labelCoeDrag")
        
        self.labelDiameter = QtWidgets.QLabel(parent=widRocketConfig)
        self.labelDiameter.setGeometry(QtCore.QRect(0, 100, 100, 16))
        self.labelDiameter.setObjectName("labelDiameter")
        
        self.editCoeDrag = QtWidgets.QLineEdit(parent=widRocketConfig)
        self.editCoeDrag.setGeometry(QtCore.QRect(100, 75, 100, 20))
        self.editCoeDrag.setObjectName("editCoeDrag")
        
        self.editDiameter = QtWidgets.QLineEdit(parent=widRocketConfig)
        self.editDiameter.setGeometry(QtCore.QRect(100, 100, 100, 20))
        self.editDiameter.setObjectName("editDiameter")

        self.retranslateUi(widRocketConfig)
        QtCore.QMetaObject.connectSlotsByName(widRocketConfig)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.labelRocketName.setText(_translate("widget", "Rocket Name:"))
        self.labelRocketMass.setText(_translate("widget", "Rocket Mass (kg)"))
        self.labelCoeDrag.setText(_translate("widget", "Cd"))
        self.labelDiameter.setText(_translate("widget", "Diameter (m)"))
